name: Gradle Cache
description: Gradle Home Cache
runs:
  using: "composite"
  steps:
    - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
      with:
        path: /root/.gradle/wrapper/dists
        key: cache-gradle-${{ github.workflow }}-${{ github.job }}-ghcr.io/build-trust/ockam-builder@sha256:3ea4c222da220c69b62a60d42d83769286e07bf8e41ef7cfdbeba18b7f22a488
        restore-keys: |
          cache-gradle-${{ github.workflow }}-${{ github.job }}-ghcr.io/build-trust/ockam-builder@sha256:3ea4c222da220c69b62a60d42d83769286e07bf8e41ef7cfdbeba18b7f22a488
          cache-gradle-${{ github.workflow }}-${{ github.job }}-
          cache-gradle-${{ github.workflow }}-
          cache-gradle-
