[package]
name = "tunnel_example"
version = "0.0.0"
authors = ["Ockam Developers"]
edition = "2018"
publish = false

[dependencies]
ockam = { path = "../../../ockam" }
rand = "0.8"

[package.metadata.release]
release = false
