name: docker_base
on:
  workflow_dispatch:
  push:

jobs:
  docker_base:
    runs-on: ubuntu-20.04
    environment:
      name: artifacts

    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          repository: ockam-network/artifacts
          event-type: docker_base
          client-payload: '{"sha": "${{ github.sha }}"}'
