name: Documentation

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/documentation.yml'
      - 'documentation/use-cases/**.md'
      - 'documentation/guides/rust/**.md'
      - 'tools/docs/**'
      - '**.rs'
      - '**.toml'
      - '**/Cargo.lock'
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/actions/**'
  push:
    paths:
      - '.github/workflows/documentation.yml'
      - 'documentation/use-cases/**.md'
      - 'documentation/guides/rust/**.md'
      - 'tools/docs/**'
      - '**.rs'
      - '**.toml'
      - '**/Cargo.lock'
      - '**.gradle'
      - 'tools/gradle/**'
      - 'gradlew'
      - 'gradlew.bat'
      - '.github/actions/**'
  schedule:
    - cron: '0 1 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check_examples_in_guides:
    name: Documentation - Check Examples
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/build-trust/ockam-builder@sha256:3ea4c222da220c69b62a60d42d83769286e07bf8e41ef7cfdbeba18b7f22a488
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - uses: ./.github/actions/gradle_cache
      - uses: ./.github/actions/cargo_home_cache
      - uses: ./.github/actions/cargo_target_dir_cache

      - name: Check that example source and guide code blocks match
        run: OCKAM_HOME=$PWD tools/docs/check_documentation.sh

      - name: Run Get Started examples
        run: OCKAM_HOME=$PWD tools/docs/run_examples.sh

      - name: Run Kafka examples
        run: OCKAM_HOME=$PWD tools/docs/run_kafka_example.sh

      - uses: ./.github/actions/cargo_target_dir_pre_cache
