name: Semgrep

# Semgrep is a static analysis tool to lint code for patterns we want to forbid
# https://github.com/returntocorp/semgrep

permissions:
  contents: read

on:
  workflow_dispatch:
  pull_request:
  merge_group:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Semgrep - Lint
    runs-on: ubuntu-20.04
    container:
      image: returntocorp/semgrep
    steps:
      - name: Check out ockam repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
      - name: Run Semgrep
        # .semgrepignore is not processed outside of working directory. See https://github.com/returntocorp/semgrep/issues/5669
        run: |
          mv tools/semgrep/.semgrepignore . & \
          semgrep --verbose --config="r2c" --config="tools/semgrep/rules/example.yaml"
