name: Shellcheck

# shellcheck gives warnings and suggestions for bash/sh shell scripts.
# https://github.com/koalaman/shellcheck

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: SHA to test workflow
  merge_group:
    paths:
      - "**.sh"
  pull_request:
    paths:
      - "**.sh"
  push:
    branches:
      - develop
  schedule:
    - cron: "0 1 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}
  cancel-in-progress: true

jobs:
  lint:
    name: Shellcheck - Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Check out ockam repository
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247
        with:
          ref: ${{ github.event.inputs.commit_sha }}
      - name: Run ShellCheck on all '.sh' files
        run: shellcheck -S error $(find . -iname "*.sh")
