name: Typos
on: pull_request

permissions:
  contents: read

jobs:
  run:
    name: Spell check with Typos
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Check spelling
        uses: crate-ci/typos@c16dc8f5b4a7ad6211464ecf136c69c851e8e83c
        with:
          config: tools/typos/typos.toml
